[package]
name = "mmapp-rust"
version = "0.1.0"
authors = ["Krzysztof Darasz <krzysztof.darasz@___.com>"]
edition = "2018"

[lib]
name = "mmap_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.13.2", features = ["extension-module"] }
